apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: acs-runtime-evaluator
rules:
  - apiGroups: ["policy.stackrox.io"]
    resources: ["clusterstackroxpolicies", "stackroxpolicies"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["policy.stackrox.io"]
    resources: ["clusterstackroxpolicies/status", "stackroxpolicies/status"]
    verbs: ["get", "update", "patch"]
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: acs-runtime-evaluator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: acs-runtime-evaluator
subjects:
  - kind: ServiceAccount
    name: acs-runtime-evaluator
    namespace: acs-next
