apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: broker-jetstream-data
  namespace: acs-next
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: gp3-csi
