apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: acs-admission-controller
webhooks:
  - name: admission-controller.acs-next.svc
    admissionReviewVersions: ["v1"]
    sideEffects: None
    timeoutSeconds: 10
    failurePolicy: Ignore
    clientConfig:
      service:
        name: acs-admission-controller
        namespace: acs-next
        path: /validate
        port: 443
      caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUZMVENDQXhXZ0F3SUJBZ0lVZHU1VUUzMnM3NUp0U1BkVnRJeWU0Rm52NUU0d0RRWUpLb1pJaHZjTkFRRUwKQlFBd0pqRWtNQ0lHQTFVRUF3d2JRVU5USUVGa2JXbHpjMmx2YmlCRGIyNTBjbTlzYkdWeUlFTkJNQjRYRFRJMgpNRE13TnpBeE5URXpPVm9YRFRNMk1ETXdOREF4TlRFek9Wb3dKakVrTUNJR0ExVUVBd3diUVVOVElFRmtiV2x6CmMybHZiaUJEYjI1MGNtOXNiR1Z5SUVOQk1JSUNJakFOQmdrcWhraUc5dzBCQVFFRkFBT0NBZzhBTUlJQ0NnS0MKQWdFQXVKN2hJOGF1TWt2VGhQQXluT2R3SCt0QUYrYVNYLzltSUpwRDlOYTA1bTY3R2RZWVd5QWR0bnBWNG9zbgpuTzBYcXhMajcyLzhNTzYyeDJQeGNDT2VHS1ppbTR3L3gxbjd0M1RoUXBrNHZsMTA0bEtXU2s4MzdkeUdKWWhFCnl5eTNhUi9kbXcyRDVDamFlQ0J0UXU1N2pVeUs2UEtJUXU5Q2wzTVFsL1ZrSjc2T0pPNTZkUEpzaHlhNjBLNTgKZ09OUWZDa0VjazBBdnFkdDVJUUo0YTFmVUhSZkZNOFRhRjhkVHo5UGtvNjUzaU1YRURwcVV5TW4zQlowcXN3SQpDZVdaWXFic2Z1dWxUR2Q0b0M3VVNubjU0ODA0T21mMlg1anplMmZrekE5VFZjUUgwVVNDaFZoWEF3alhia3pyCjlFUS9nZ0NpaVhOUU1yM1V3OGZxczlQeWY5UUZEYUxDbjQvUEV2dXc1cHltZUVvVTNSajVyNHd4NjZJVmxTbWYKcWJ2N01ZMlIrMDdyMjZKQUhSaDJOb0xwM2pLR2x3VXkvTVVUdWJrSlJnVWVEY3FRNHUrZjU5Yjl4THRRcTNLMgpaanlmeWt3OWhoNVpwanQvelRISXpveCt5QjEyeGZyY3hnejkzMVhCY2t6MDZKcFBSNVVnamxoU3hlZWJ4a2xXCkk4RVd2MWNXWUZjeHZqZjdacjNlWXMyaHBjckVsUFNkd0JRQUg5KzBUUzFXNDM3QnRab2U5QVZmZGF2MDJrdDMKVXdrc3FnWnlKRVlkcCtvaVhxUE5kY2VNek9vQk5XSDd2L3dwZnhKbkNTZTVkWUx0WWZnNmJqU0FTNUIrOG0vSAphVHEwV2ZRVjJQbyt1YkFQOE8rRUVZbTFPeERGTWdnaEcreHJBYXF3bXl3bkpNTUNBd0VBQWFOVE1GRXdIUVlEClZSME9CQllFRkVTNWdaQ0YvbEVBVzVqSVBoaUJYTFJobGsrSk1COEdBMVVkSXdRWU1CYUFGRVM1Z1pDRi9sRUEKVzVqSVBoaUJYTFJobGsrSk1BOEdBMVVkRXdFQi93UUZNQU1CQWY4d0RRWUpLb1pJaHZjTkFRRUxCUUFEZ2dJQgpBRnlZOWppaHlPZjRaaG56aGU4Qk56SEhzZDNsVlNDR2hyTDQwTVZyWlJhUUhBYk5Mc1JKTmE1SkMwREk1dStnCkNHRWlseFZ0SkZ0dlliUjZIbmxQRlJJLzI4MmNyazRtV0VuR0dQSFRWc05ydkxKR2gyMnZpYVVGVFBlUW5adUcKbnlmNXgwZGhkb2xzMGFhcnRnL093QklqbmdmdjFxaGMySmpkTlNaWkFPOGp4ZWVyV01WTXhOTEpuS0ppTWdSZwpMbUdrU3UxL0tTMnVLS3JLV2xwbTRhM0RIUkFST2YrVHIyc0l1WDFVYnR6bnRGRkl5VHJueXFmRGhSSjg2UHRmClpOSW1RdFpWenBxODNYUTJPQ0F2dXZxTW85SWlkdjJ1aVd2d01aUDBYaEt5anlmZ044VUduRSthOFV1NDNHTUUKQXFJZWxQK0R0c2NzOStIbG4vMzJWVG1aYlVNYWlPeFVJUGJHdzNKb0MyOXEyOWEvVFJJNDYwOE9GdjhnYTdaMgpBVkVEQWEySjBMZjBmU2hpckgwZWhPMWhDSEdUbVg3dVhBSjVDdlppeFhzc09WODZERFdCdDk1L0dXTC9IMkhHCmQxTFgzUVdJL2xycWhzcWtzZm1rL1ExUS9tck1iVWFGM1dEbW5WZlpoMUFIWEVqMXNvbDV4ekNOSFhtc1RKaXYKTDVCdnlscDNHaHQ3NGc2L1FtRGFYRFpseWoxdk9WVnh5dmdPTmdhV0YyRk1aQnU3eHZhVlFlSCt6Z3NmVEJ3RApoRHczeUwxempJZ2hSQXBrMWkrSWVyQmNHb0hGdmMvaUZPb21EK1EremFvcUtYMHR2clMvaHhqbFY5Tk1CSTlNCklGQnpmVUxGdWtJaG9aNVNQa3ZlNU5maHZkYW93WFM5dzlyYXdlVlVUcmlrCi0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
    rules:
      - apiGroups: [""]
        apiVersions: ["v1"]
        operations: ["CREATE"]
        resources: ["pods"]
        scope: Namespaced
    namespaceSelector:
      matchLabels:
        acs-next.stackrox.io/enforce: "true"
