apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: registry-data
  namespace: dev-registry
spec:
  storageClassName: gp3-csi
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Gi
