apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - no-privileged-containers.yaml
  - no-latest-tag.yaml
  - require-resource-limits.yaml
  - no-host-network.yaml
  - suspicious-process.yaml
  - sensitive-port-listen.yaml
