//go:build !ignore_autogenerated

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"acs-next.stackrox.io/apis/common/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterScopedViolationMetrics) DeepCopyInto(out *ClusterScopedViolationMetrics) {
	*out = *in
	if in.LastViolationTime != nil {
		in, out := &in.LastViolationTime, &out.LastViolationTime
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterScopedViolationMetrics.
func (in *ClusterScopedViolationMetrics) DeepCopy() *ClusterScopedViolationMetrics {
	if in == nil {
		return nil
	}
	out := new(ClusterScopedViolationMetrics)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterStackroxPolicy) DeepCopyInto(out *ClusterStackroxPolicy) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterStackroxPolicy.
func (in *ClusterStackroxPolicy) DeepCopy() *ClusterStackroxPolicy {
	if in == nil {
		return nil
	}
	out := new(ClusterStackroxPolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ClusterStackroxPolicy) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterStackroxPolicyList) DeepCopyInto(out *ClusterStackroxPolicyList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ClusterStackroxPolicy, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterStackroxPolicyList.
func (in *ClusterStackroxPolicyList) DeepCopy() *ClusterStackroxPolicyList {
	if in == nil {
		return nil
	}
	out := new(ClusterStackroxPolicyList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ClusterStackroxPolicyList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterStackroxPolicySpec) DeepCopyInto(out *ClusterStackroxPolicySpec) {
	*out = *in
	if in.Categories != nil {
		in, out := &in.Categories, &out.Categories
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.LifecycleStages != nil {
		in, out := &in.LifecycleStages, &out.LifecycleStages
		*out = make([]v1.LifecycleStage, len(*in))
		copy(*out, *in)
	}
	if in.Exclusions != nil {
		in, out := &in.Exclusions, &out.Exclusions
		*out = make([]v1.Exclusion, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Scope != nil {
		in, out := &in.Scope, &out.Scope
		*out = make([]v1.Scope, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.EnforcementActions != nil {
		in, out := &in.EnforcementActions, &out.EnforcementActions
		*out = make([]v1.EnforcementAction, len(*in))
		copy(*out, *in)
	}
	if in.Notifiers != nil {
		in, out := &in.Notifiers, &out.Notifiers
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.PolicySections != nil {
		in, out := &in.PolicySections, &out.PolicySections
		*out = make([]v1.PolicySection, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.MitreAttackVectors != nil {
		in, out := &in.MitreAttackVectors, &out.MitreAttackVectors
		*out = make([]v1.MitreAttackVectors, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterStackroxPolicySpec.
func (in *ClusterStackroxPolicySpec) DeepCopy() *ClusterStackroxPolicySpec {
	if in == nil {
		return nil
	}
	out := new(ClusterStackroxPolicySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterStackroxPolicyStatus) DeepCopyInto(out *ClusterStackroxPolicyStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.LastEvaluated != nil {
		in, out := &in.LastEvaluated, &out.LastEvaluated
		*out = (*in).DeepCopy()
	}
	if in.ViolationMetrics != nil {
		in, out := &in.ViolationMetrics, &out.ViolationMetrics
		*out = new(ClusterScopedViolationMetrics)
		(*in).DeepCopyInto(*out)
	}
	if in.RecentViolations != nil {
		in, out := &in.RecentViolations, &out.RecentViolations
		*out = make([]RecentViolation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterStackroxPolicyStatus.
func (in *ClusterStackroxPolicyStatus) DeepCopy() *ClusterStackroxPolicyStatus {
	if in == nil {
		return nil
	}
	out := new(ClusterStackroxPolicyStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NamespaceScopedViolationMetrics) DeepCopyInto(out *NamespaceScopedViolationMetrics) {
	*out = *in
	if in.LastViolationTime != nil {
		in, out := &in.LastViolationTime, &out.LastViolationTime
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NamespaceScopedViolationMetrics.
func (in *NamespaceScopedViolationMetrics) DeepCopy() *NamespaceScopedViolationMetrics {
	if in == nil {
		return nil
	}
	out := new(NamespaceScopedViolationMetrics)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RecentViolation) DeepCopyInto(out *RecentViolation) {
	*out = *in
	out.Resource = in.Resource
	in.Timestamp.DeepCopyInto(&out.Timestamp)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RecentViolation.
func (in *RecentViolation) DeepCopy() *RecentViolation {
	if in == nil {
		return nil
	}
	out := new(RecentViolation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StackroxPolicy) DeepCopyInto(out *StackroxPolicy) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StackroxPolicy.
func (in *StackroxPolicy) DeepCopy() *StackroxPolicy {
	if in == nil {
		return nil
	}
	out := new(StackroxPolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *StackroxPolicy) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StackroxPolicyList) DeepCopyInto(out *StackroxPolicyList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]StackroxPolicy, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StackroxPolicyList.
func (in *StackroxPolicyList) DeepCopy() *StackroxPolicyList {
	if in == nil {
		return nil
	}
	out := new(StackroxPolicyList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *StackroxPolicyList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StackroxPolicySpec) DeepCopyInto(out *StackroxPolicySpec) {
	*out = *in
	if in.Categories != nil {
		in, out := &in.Categories, &out.Categories
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.LifecycleStages != nil {
		in, out := &in.LifecycleStages, &out.LifecycleStages
		*out = make([]v1.LifecycleStage, len(*in))
		copy(*out, *in)
	}
	if in.Exclusions != nil {
		in, out := &in.Exclusions, &out.Exclusions
		*out = make([]v1.Exclusion, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Scope != nil {
		in, out := &in.Scope, &out.Scope
		*out = make([]v1.NamespaceScopedScope, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.EnforcementActions != nil {
		in, out := &in.EnforcementActions, &out.EnforcementActions
		*out = make([]v1.EnforcementAction, len(*in))
		copy(*out, *in)
	}
	if in.Notifiers != nil {
		in, out := &in.Notifiers, &out.Notifiers
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.PolicySections != nil {
		in, out := &in.PolicySections, &out.PolicySections
		*out = make([]v1.PolicySection, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.MitreAttackVectors != nil {
		in, out := &in.MitreAttackVectors, &out.MitreAttackVectors
		*out = make([]v1.MitreAttackVectors, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StackroxPolicySpec.
func (in *StackroxPolicySpec) DeepCopy() *StackroxPolicySpec {
	if in == nil {
		return nil
	}
	out := new(StackroxPolicySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StackroxPolicyStatus) DeepCopyInto(out *StackroxPolicyStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.LastEvaluated != nil {
		in, out := &in.LastEvaluated, &out.LastEvaluated
		*out = (*in).DeepCopy()
	}
	if in.ViolationMetrics != nil {
		in, out := &in.ViolationMetrics, &out.ViolationMetrics
		*out = new(NamespaceScopedViolationMetrics)
		(*in).DeepCopyInto(*out)
	}
	if in.RecentViolations != nil {
		in, out := &in.RecentViolations, &out.RecentViolations
		*out = make([]RecentViolation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StackroxPolicyStatus.
func (in *StackroxPolicyStatus) DeepCopy() *StackroxPolicyStatus {
	if in == nil {
		return nil
	}
	out := new(StackroxPolicyStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ViolationResource) DeepCopyInto(out *ViolationResource) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ViolationResource.
func (in *ViolationResource) DeepCopy() *ViolationResource {
	if in == nil {
		return nil
	}
	out := new(ViolationResource)
	in.DeepCopyInto(out)
	return out
}
